-- Job instance table
CREATE TABLE BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    VERSION INTEGER,
    JOB_NAME VARCHAR(100) NOT NULL,
    JOB_KEY VARCHAR(32) NOT NULL
);

-- Job execution table
CREATE TABLE BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    VERSION INTEGER,
    JOB_INSTANCE_ID INTEGER NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    START_TIME DATETIME,
    END_TIME DATETIME,
    STATUS VARCHAR(10),
    EXIT_CODE VARCHAR(250),
    EXIT_MESSAGE VARCHAR(250),
    LAST_UPDATED DATETIME,
    FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

-- Job execution parameters
CREATE TABLE BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID INTEGER NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(6) NOT NULL,
    PARAMETER_VALUE VARCHAR(250),
    PARAMETER_VALUE_DATE DATETIME,
    PARAMETER_VALUE_LONG INTEGER,
    PARAMETER_VALUE_DOUBLE REAL,
    IDENTIFYING CHAR(1) NOT NULL,
    FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

-- Step execution table
CREATE TABLE BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    VERSION INTEGER NOT NULL,
    STEP_NAME VARCHAR(100) NOT NULL,
    JOB_EXECUTION_ID INTEGER NOT NULL,
    START_TIME DATETIME,
    END_TIME DATETIME,
    STATUS VARCHAR(10),
    COMMIT_COUNT INTEGER,
    READ_COUNT INTEGER,
    FILTER_COUNT INTEGER,
    WRITE_COUNT INTEGER,
    READ_SKIP_COUNT INTEGER,
    WRITE_SKIP_COUNT INTEGER,
    PROCESS_SKIP_COUNT INTEGER,
    ROLLBACK_COUNT INTEGER,
    EXIT_CODE VARCHAR(250),
    EXIT_MESSAGE VARCHAR(250),
    LAST_UPDATED DATETIME,
    CREATE_TIME DATETIME,
    FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

-- Job execution context
CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID INTEGER PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(250),
    SERIALIZED_CONTEXT TEXT,
    FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

-- Step execution context
CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID INTEGER PRIMARY KEY,
    SHORT_CONTEXT VARCHAR(250),
    SERIALIZED_CONTEXT TEXT,
    FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);

-- Sequences (Spring Batch uses these for generating IDs)
CREATE TABLE BATCH_JOB_SEQ (
    ID INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE BATCH_STEP_EXECUTION_SEQ (
    ID INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE BATCH_JOB_EXECUTION_SEQ (
    ID INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE BATCH_JOB_INSTANCE_SEQ (
    ID INTEGER PRIMARY KEY AUTOINCREMENT
);